package com.cmcilroy.medicines_shortages_assistant.services;

import com.cmcilroy.medicines_shortages_assistant.domain.entities.PharmacyDrugAvailabilityEntity;

public interface PharmacyDrugAvailabilityService {

    PharmacyDrugAvailabilityEntity createPharmacyDrugAvailability(PharmacyDrugAvailabilityEntity pharmacyDrugAvailability);
}
